unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.user_signup, name="signup"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout")
]

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/dwes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("memora.urls", namespace="memora")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/memora/urls.py
from django.urls import path

from . import views

app_name = "memora"

urlpatterns = [
    path("", views.index, name="index"),
    path("notes/", views.notes, name="notes"),
    path("notes/<int:note_id>/", views.detail, name="detail"),
    path("notes/create/", views.create_note, name="create_note"),
    path("notes/<int:note_id>/edit/", views.edit_note, name="edit_note"),
    path("notes/<int:note_id>/delete/", views.delete_note, name="delete_note"),

    path("upload/image", views.upload_image, name="upload_image")
]

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/accounts/models.py
from django.db import models

# Create your models here.

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/memora/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Note(models.Model):
    note = models.TextField(verbose_name="Nota o recordatorio")
    pub_date = models.DateTimeField("date published")
    category = models.ForeignKey(Category, verbose_name="Categoría", on_delete=models.CASCADE)

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/memora/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ["note", "category"]


class UploadImageForm(forms.Form):
    title = forms.CharField(max_length=50)
    image = forms.FileField()

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import SignupForm, LoginForm


def user_signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("accounts:login"))
    else:
        form = SignupForm()
    return render(request, "accounts/signup.html", {"form": form})


def user_login(request):
    message = ""
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse("memora:index"))
            else:
                message = "Nombre y/o contraseña no válidos"
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form, "message": message})


@login_required
def user_logout(request):
    logout(request)
    return render(request, "accounts/logout.html")

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/memora/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import Note
from .forms import NoteForm, UploadImageForm
from .utils import handle_upload_file


def index(request):
    return render(request, "memora/index.html")


def notes(request):
    notes = Note.objects.all()
    return render(request, "memora/list.html", {"notes": notes})


def detail(request, note_id):
    try:
        note = Note.objects.get(id=note_id)
    except Note.DoesNotExist:
        raise Http404("La nota no existe")

    return render(request, "memora/detail.html", {"note": note})


@login_required
def create_note(request):
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.pub_date = timezone.now()
            note.save()
            return redirect(reverse("memora:notes"))
    else:
        form = NoteForm()

    return render(
        request,
        "memora/note_form.html",
        {"form": form, "action": reverse("memora:create_note")}
    )


def edit_note(request, note_id):
    try:
        note = Note.objects.get(id=note_id)
    except Note.DoesNotExist:
        raise Http404("La nota no existe")

    if request.method == "POST":
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect(reverse("memora:notes"))
    else:
        form = NoteForm(instance=note)

    return render(
        request,
        "memora/note_form.html",
        {"form": form, "action": reverse("memora:edit_note", args=(note_id,))}
    )


def delete_note(request, note_id):
    try:
        Note.objects.get(id=note_id).delete()
    except Note.DoesNotExist:
        raise Http404("La nota no existe")

    return redirect(reverse("memora:notes"))


def upload_image(request):
    if request.method == "POST":
        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            handle_upload_file(form.cleaned_data["title"], request.FILES["image"])
            return redirect(reverse("memora:index"))
    else:
        form = UploadImageForm()

    return render(request, "memora/image_form.html", {"form": form})

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="container-md my-4">
  <div class="row">
    <div class="col-12">
      {% if message %}
      <p class="alert alert-danger">{{ message }}</p>
      {% endif %}
      <form method="post">
	{% csrf_token %}
	{{ form }}
	<button type="submit" class="btn btn-primary">Login</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% block content %}
<div class="container-md my-4">
  <div class="row">
    <div class="col-12">
      <p class="alert alert-info">Has cerrado tu sesión... ¡hasta pronto!</p>
      <a href="{% url 'memora:index' %}">Volver</a>
    </div>
  </div>
</div>
{% endblock %}

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<div class="container-md my-4">
  <div class="row">
    <div class="col-12">

      <h2>Regístrate</h2>

      <form method="post">
	{% csrf_token %}
	{{ form }}
	<button type="submit" class="btn btn-primary">Regístrate</button>
      </form> 
    </div>
  </div>
</div>
{% endblock %}

unidades/07_django/ninja_trainings/13_django_notas_con_imagenes/todo/dwes/memora/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Memora{% endblock %}</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Memora</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
	<ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'memora:notes' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'memora:notes' %}">Recordatorios</a>
          </li>
	  <li class="nav-item">
            <a class="nav-link" href="{% url 'memora:upload_image' %}">Subir Imagen</a>
	  </li>
	  {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'memora:create_note' %}">Añadir recordatorio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Salir</a>
          </li>
	  {% else %}
	  <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Entrar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Registrarse</a>
          </li>
	  {% endif %}
      </div>
    </div>
  </nav>

  <div class="container-fluid my-4">
    {% block content %}{% endblock %}
  </div>
</body>
</html>