unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.user_signup, name="signup"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout")
]

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/dwes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("memora.urls", namespace="memora")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/memora/urls.py
from django.urls import path

from . import views

app_name = "memora"

urlpatterns = [
    path("", views.index, name="index"),
    path("notes/", views.notes, name="notes"),
    path("notes/<int:note_id>/", views.detail, name="detail"),
    path("notes/create/", views.create_note, name="create_note"),
    path("notes/<int:note_id>/edit/", views.edit_note, name="edit_note"),
    path("notes/<int:note_id>/delete/", views.delete_note, name="delete_note"),

    path("upload/image", views.upload_image, name="upload_image")
]

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/accounts/models.py
from django.db import models

# Create your models here.

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/memora/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Note(models.Model):
    note = models.TextField(verbose_name="Nota o recordatorio")
    pub_date = models.DateTimeField("date published")
    category = models.ForeignKey(Category, verbose_name="Categoría", on_delete=models.CASCADE)

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/memora/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ["note", "category"]


class UploadImageForm(forms.Form):
    title = forms.CharField(max_length=50)
    image = forms.FileField()

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import SignupForm, LoginForm


def user_signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("accounts:login"))
    else:
        form = SignupForm()
    return render(request, "accounts/signup.html", {"form": form})


def user_login(request):
    message = ""
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse("memora:index"))
            else:
                message = "Nombre y/o contraseña no válidos"
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form, "message": message})


@login_required
def user_logout(request):
    logout(request)
    return render(request, "accounts/logout.html")

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/memora/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import Note
from .forms import NoteForm, UploadImageForm
from .utils import handle_upload_file


def index(request):
    return render(request, "memora/index.html")


def notes(request):
    notes = Note.objects.all()
    return render(request, "memora/list.html", {"notes": notes})


def detail(request, note_id):
    try:
        note = Note.objects.get(id=note_id)
    except Note.DoesNotExist:
        raise Http404("La nota no existe")

    return render(request, "memora/detail.html", {"note": note})


@login_required
def create_note(request):
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.pub_date = timezone.now()
            note.save()
            return redirect(reverse("memora:notes"))
    else:
        form = NoteForm()

    return render(
        request,
        "memora/note_form.html",
        {"form": form, "action": reverse("memora:create_note")}
    )


def edit_note(request, note_id):
    try:
        note = Note.objects.get(id=note_id)
    except Note.DoesNotExist:
        raise Http404("La nota no existe")

    if request.method == "POST":
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect(reverse("memora:notes"))
    else:
        form = NoteForm(instance=note)

    return render(
        request,
        "memora/note_form.html",
        {"form": form, "action": reverse("memora:edit_note", args=(note_id,))}
    )


def delete_note(request, note_id):
    try:
        Note.objects.get(id=note_id).delete()
    except Note.DoesNotExist:
        raise Http404("La nota no existe")

    return redirect(reverse("memora:notes"))


def upload_image(request):
    if request.method == "POST":
        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            handle_upload_file(form.cleaned_data["title"], request.FILES["image"])
            return redirect(reverse("memora:index"))
    else:
        form = UploadImageForm()

    return render(request, "memora/image_form.html", {"form": form})

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/memora/templates/memora/detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Detalles de la nota</h5>
      <h6 class="card-subtitle mb-2 text-body-secondary">{{ note.category.name }}</h6>
      <p class="card-text">{{ note.note }}</p>
    </div>
  </div>
</div>
{% endblock %}

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/memora/templates/memora/image_form.html
{% extends "base.html" %}

{% block content %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Subir">
</form>
{% endblock %}

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/memora/templates/memora/index.html
{% extends "base.html" %}

{% block content %}
<div class="container-md">
  <div class="col-12">
    <h2 class="display-6">Bienvenid@s a Memora</h2>
  </div>
</div>
{% endblock %}

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/memora/templates/memora/list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>Listado de notas</h1>
  <ul class="list-group">
    {% for n in notes %}
    <li class="list-group-item">
      {{ n.note }}<br>
      <small>
	<a class="link-offset-2 link-underline link-underline-opacity-0"
	   href="{% url 'memora:detail' n.id %}">
	  Detalles
	</a>
	<a class="link-offset-2 link-underline link-underline-opacity-0 ms-4"
	   href="{% url 'memora:edit_note' n.id %}">
	  Editar 
	</a>
	<a class="link-danger link-offset-2 link-underline link-underline-opacity-0 ms-4"
	   href="{% url 'memora:delete_note' n.id %}">
	  Eliminar
	</a>
      </small>
    </li>
    {% empty %}
      <li class="list-group-item">No hay notas</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

unidades/07_django/ninja_trainings/12_django_upload_file/done/dwes/memora/templates/memora/note_form.html
{% extends "base.html" %}

{% block content %}
<form action="{{ action }}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Enviar">
</form>
{% endblock %}