unidades/07_django/ninja_trainings/11_django_many_to_many_m2m/todo/dwes_m2m/dwes_m2m/dwes_m2m/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("enrollment.urls", namespace="enrollment"))
]

unidades/07_django/ninja_trainings/11_django_many_to_many_m2m/todo/dwes_m2m/dwes_m2m/enrollment/urls.py
from django.urls import path

from . import views

app_name = "enrollment"

urlpatterns = [
    path("", views.index, name="index"),

    path("subjects/list/", views.subject_list, name="subject_list"),
    path("subjects/<int:id>/detail/", views.subject_detail, name="subject_detail"),
    path("subjects/create/", views.subject_create, name="subject_create"),
    path("subjects/<int:id>/enroll/student/", views.subject_enroll_student, name="subject_enroll_student"),

    path("students/create/", views.student_create, name="student_create"),
]

unidades/07_django/ninja_trainings/11_django_many_to_many_m2m/todo/dwes_m2m/dwes_m2m/enrollment/models.py
from django.db import models


class Student(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    age = models.IntegerField()

    def __str__(self):
        return f"{self.surname}, {self.name}"


class Subject(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    students = models.ManyToManyField(
        Student,
        through="Enrollment"
    )


class Enrollment(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    enrolled_date = models.DateField(auto_now_add=True)
    morning_session = models.BooleanField()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=(["student", "subject"]),
                name="subject_student_enrollment"
            )
        ]

unidades/07_django/ninja_trainings/11_django_many_to_many_m2m/todo/dwes_m2m/dwes_m2m/enrollment/forms.py
from django import forms

from .models import Subject, Student, Enrollment


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ["name", "description"]


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ["name", "surname", "age"]


class EnrollmentForm(forms.ModelForm):
    class Meta:
        model = Enrollment
        fields = ["student", "morning_session"]

unidades/07_django/ninja_trainings/11_django_many_to_many_m2m/todo/dwes_m2m/dwes_m2m/enrollment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.db.utils import IntegrityError

from .models import Subject, Enrollment
from .forms import SubjectForm, StudentForm, EnrollmentForm


def index(request):
    return render(request, "enrollment/index.html")


def subject_list(request):
    subjects = Subject.objects.all()
    return render(request, "enrollment/subject_list.html", {"subjects": subjects})


def subject_detail(request, id):
    subject = get_object_or_404(Subject, id=id)
    return render(request, "enrollment/subject_detail.html", {"subject": subject})


def subject_create(request):
    if request.method == "POST":
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("enrollment:subject_list"))
    else:
        form = SubjectForm()

    return render(
        request,
        "enrollment/form.html",
        {"form": form, "header": "Añadir Materia"}
    )


def subject_enroll_student(request, id):
    subject = get_object_or_404(Subject, id=id)
    message = ""

    if request.method == "POST":
        form = EnrollmentForm(request.POST)
        if form.is_valid():
            try:
                Enrollment.objects.create(
                    student=form.cleaned_data["student"],
                    subject=subject,
                    morning_session=form.cleaned_data["morning_session"]
                )
                return redirect(reverse("enrollment:subject_detail", args=(id,)))
            except IntegrityError:
                message = "Ya existe el alumno en el curo"
    else:
        form = EnrollmentForm()

    return render(
        request,
        "enrollment/form.html",
        {"form": form, "header": "Matricular Alumnado", "message": message}
    )


def student_create(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("enrollment:subject_list"))
    else:
        form = StudentForm()

    return render(
        request,
        "enrollment/form.html",
        {"form": form, "header": "Añadir Alumnado"}
    )

unidades/07_django/ninja_trainings/11_django_many_to_many_m2m/todo/dwes_m2m/dwes_m2m/enrollment/templates/enrollment/form.html
{% extends "base.html" %}

{% block content %}
<div class="container-md my-4">
  <div class="row">
    <div class="col-12">
      <h1>{{ header }}</h1>

      {% if message %}
      <p class="alert alert-danger">{{ message }}</p>
      {% endif %}
      
      <form method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Submit">
      </form>
    </div>
  </div>
</div>
{% endblock %}

unidades/07_django/ninja_trainings/11_django_many_to_many_m2m/todo/dwes_m2m/dwes_m2m/enrollment/templates/enrollment/index.html
{% extends "base.html" %}

{% block content %}
<div class="container-md">
  <div class="col-12">
    <h2 class="display-6">Bienvenid@s a Enrollment</h2>
  </div>
</div>
{% endblock %}

unidades/07_django/ninja_trainings/11_django_many_to_many_m2m/todo/dwes_m2m/dwes_m2m/enrollment/templates/enrollment/subject_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Detalles de la materia</h5>
      <h6 class="card-subtitle mb-2 text-body-secondary">{{ subject.name }}</h6>
      <p class="card-text">{{ subject.description }}</p> 
    </div>
  </div>
  
  {% if subject.students.exists %}
  <ul class="list-group list-group-flush">
    {% for s in subject.students.all %}
    <li class="list-group-item">
      {{ s.name }} {{ s.surname }}
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p class="alert alert-info">No hay estudiantes matriculados a esta materia</p>
  {% endif %}
  <a href="{% url 'enrollment:subject_enroll_student' subject.id %}">Matricular alumnado</a>
</div>
{% endblock %}

unidades/07_django/ninja_trainings/11_django_many_to_many_m2m/todo/dwes_m2m/dwes_m2m/enrollment/templates/enrollment/subject_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>Listado de materias</h1>
  <ul class="list-group">
    {% for s in subjects %}
    <li class="list-group-item">
      {{ s.name}}<br>
      <small>
	<a class="link-offset-2 link-underline link-underline-opacity-0"
	   href="{% url 'enrollment:subject_detail' s.id %}">
	  Detalles
	</a>
      </small>
    </li>
    {% empty %}
      <li class="list-group-item">No hay materias</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}